name: Sync Fork
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checking repository
        uses: actions/checkout@v3
      - name: Sync and merge upstream repository with your current repository
      # You may pin to the exact commit or the version.
      # uses: dabreadman/sync-upstream-repo@fc5fe9952946b1daaafd9abd7fcd7e260b81ddbe
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/APHRC-DSE/Supermarket-Project-Insights_Grocery_Purchase_Patterns
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: master
          # Branch to merge into downstream
          downstream_branch: master 
          # GitHub Bot token
          token: ${{secrets.GITHUB_TOKEN}}
          # Git fetch arguments
          #fetch_args: # optional, default is 
          # Git merge arguments
          #merge_args: # optional, default is 
          # Git push arguments
          #push_args: # optional, default is 
          # Toggle to spawn `sync-upstream-repo` with time logs
          spawn_logs: true
          
          
        
